[general]
import = [ "~/.config/alacritty/ubuntu-theme.toml" ]

[selection]
save_to_clipboard = true

[scrolling]
history = 50000

[font]
size = 14
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }

[window]
dimensions = { columns = 120, lines = 30 }
option_as_alt = "OnlyLeft"

[keyboard]
bindings = [
    # beginning-of-line
    { key = "Left", mods = "Command", chars = "\u001bOH" },
    # end-of-line
    { key = "Right", mods = "Command", chars = "\u001bOF" },
    # backward word
    { key = "Left", mods = "Option", chars = "\u001bb" },
    # forward-word
    { key = "Right", mods = "Option", chars = "\u001bf" },
]
